const skills = [
  ['Programming',['C++','Java','Python Basics'],'Learning',58],['Computer Science',['Data Structures & Algorithms','OOP','Problem Solving','Basic Algorithms'],'Learning',50],['Web Development',['HTML','CSS','JavaScript','Responsive Web Design','Basic React'],'Learning',55],['Database',['SQL','MySQL','Database Fundamentals'],'Learning',45],['Artificial Intelligence',['AI Tools','Generative AI','AI Prompting','AI-assisted Content Creation','AI Website Tools'],'Learning',55],['Productivity',['MS Word','MS Excel','MS PowerPoint','Google Workspace'],'Intermediate',65],['Other',['Git & GitHub Basics','VS Code','Internet & Digital Tools','Presentation Skills','Basic Cybersecurity Awareness'],'Basic',48]
];
const learning = [['C++','⌘','Building programming fundamentals and practicing problem solving.',58],['Java','☕','Learning Java syntax, OOP and programming fundamentals.',42],['DSA','⌬','Learning arrays, searching, sorting and algorithmic thinking.',45],['SQL','▦','Learning database fundamentals and queries.',42],['Web Development','◫','Learning HTML, CSS, JavaScript and responsive design.',60],['AI Tools','✦','Exploring prompting and AI-assisted workflows.',57],['Git & GitHub','⌘','Learning version control and project sharing basics.',40],['Problem Solving','↗','Practicing logical thinking through programming.',52]];
const projects = [['⌘','C++ Programming Projects','Collection of beginner programming programs created while learning C++ fundamentals.','C++'],['☕','Java Programming Projects','Java practice projects focused on programming fundamentals and object-oriented concepts.','Java'],['◫','Web Development Projects','Responsive websites and interactive web experiments created while learning front-end development.','HTML / CSS / JavaScript'],['✦','AI Tools Experiments','Experiments with AI tools, prompt engineering and AI-assisted creative workflows.','AI Tools']];
document.querySelector('#skills-grid').innerHTML=skills.map(([title,tags,level,w])=>`<article class="skill-card reveal"><h3>${title}</h3><div class="tags">${tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="level"><span>${level}</span><div class="meter"><i style="--w:${w}%"></i></div></div></article>`).join('');
document.querySelector('#learning-grid').innerHTML=learning.map(([title,icon,desc,w])=>`<article class="learning-card reveal"><span class="icon">${icon}</span><h3>${title}</h3><p>${desc}</p><span class="progress-label">IN PROGRESS</span><div class="progress"><i style="--w:${w}%"></i></div></article>`).join('');
document.querySelector('#projects-grid').innerHTML=projects.map(([icon,title,desc,tech])=>`<article class="project-card reveal"><span class="project-icon">${icon}</span><h3>${title}</h3><p>${desc}</p><div class="project-bottom"><span class="tags"><span>${tech}</span></span><span class="project-links"><a href="#contact">View Project ↗</a><a href="#contact" title="GitHub link to be added">GitHub ↗</a></span></div></article>`).join('');
const words=['C++ Developer','Java Learner','Web Developer','DSA Learner','SQL Learner','AI Tools Explorer','Creative Tech Enthusiast'];let wi=0,ci=0,deleting=false;const type=document.querySelector('#typing');function typeLoop(){const word=words[wi];type.textContent=word.slice(0,ci);if(!deleting&&ci++===word.length){deleting=true;setTimeout(typeLoop,1400);return}if(deleting&&ci--===0){deleting=false;wi=(wi+1)%words.length}setTimeout(typeLoop,deleting?38:78)}typeLoop();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
document.querySelector('.menu-toggle').addEventListener('click',e=>{const links=document.querySelector('.nav-links');links.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',links.classList.contains('open'))});document.querySelectorAll('.nav-links a').forEach(a=>a.onclick=()=>document.querySelector('.nav-links').classList.remove('open'));
window.addEventListener('scroll',()=>document.querySelector('.nav-wrap').classList.toggle('scrolled',scrollY>20));
const cursorFlameLayer=document.querySelector('.cursor-flame-layer');let flameIndex=0;let lastFlameTime=0;document.addEventListener('mousemove',e=>{const aura=document.querySelector('.cursor-aura');aura.style.left=e.clientX+'px';aura.style.top=e.clientY+'px';const now=Date.now();if(now-lastFlameTime<55)return;lastFlameTime=now;const flame=document.createElement('span');flame.className=`cursor-flame flame-${flameIndex++%4}`;flame.style.left=e.clientX+'px';flame.style.top=e.clientY+'px';flame.style.setProperty('--drift',`${(Math.random()-.5)*34}px`);cursorFlameLayer.appendChild(flame);setTimeout(()=>flame.remove(),850)});
document.querySelectorAll('.tech-orbit button').forEach(b=>b.addEventListener('mouseenter',()=>document.querySelector('.tech-tooltip').textContent=b.dataset.tech));
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,note=document.querySelector('#form-note');if(!form.checkValidity()){form.reportValidity();return}note.textContent='Thanks — your message is ready to send once an email service is connected.';note.classList.add('success')});

